### ISSUE TITLE
Skybox只能上下移动，不能左右移动视角

### ISSUE THREAD

**Issue by msxmy** [picoxr/Android_Native_VRInput_Demo#1]

**Comment by picoxr** [comment]
您好，
关于使用Pico平台开发遇到的问题，欢迎您在Pico DevAnswer论坛：https://devanswers.pico-interactive.com/index.php?qa=questions 或者我们的Jira Portal：https://picodevsupport.atlassian.net/servicedesk/customer/portal/1
我们当前不使用GitHub Issue作为问题反馈渠道。感谢理解
